import { cn } from '@/lib/utils'
import CtaTop from '@/sections/CtaTop'
import Header from '@/sections/Header'
import type { Metadata } from 'next'
import './globals.css'
// Supports weights 300-700
import '@fontsource-variable/cormorant-garamond/wght.css'
import '@fontsource-variable/jetbrains-mono/wght.css'
import '@fontsource-variable/jost/wght.css'
import '@fontsource/italiana'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es" className={cn('h-full', 'antialiased')}>
      <body className="min-h-full flex flex-col">
        <CtaTop />
        <Header />
        {children}
      </body>
    </html>
  )
}
