import { cn } from '@/lib/utils'
import Header from '@/sections/Header'
import type { Metadata } from 'next'
import { Suspense } from 'react'
import './globals.css'
// Supports weights 300-700
import Footer from '@/sections/Footer'
import '@fontsource-variable/cormorant-garamond/wght-italic.css'
import '@fontsource-variable/jetbrains-mono/wght.css'
import '@fontsource-variable/jost/wght.css'
import '@fontsource/italiana'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es" className={cn('h-full', 'antialiased')}>
      <body className="min-h-full flex flex-col">
        <Suspense fallback={null}>
          <Header brand="YEY BEAUTY" />
        </Suspense>
        {children}
        <Footer brand="YEY BEAUTY" />
      </body>
    </html>
  )
}
